spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btl_sqa
    username: root
    password: 28022001
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  sql:
    init:
      data-locations: classpath:exampledata.sql
      mode: never
  main:
    allow-circular-references: true
  #MAIL
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${SPRING_EMAIL_USERNAME:daint.dev@gmail.com}
    password: ${SPRING_EMAIL_PASSWORD:ojflsfyzqcywqwge}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  data:
    redis:
      port: 6379
      host: localhost
server:
  port: 8081
